### ISSUE TITLE
Feature request: support CLI install in existing folder

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [skeletonlabs/create-skeleton-app#2]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

It would be nice if Skeleton could support an existing folder install, I know SvelteKit allows this (not specifying a folder in the npm command and then not specifying a name when asked for the folder).

When done in Skeleton this gives an error: `Install directory already exists!`

### What type of pull request would this be?

None

**Comment by endigo9740** [comment]
@henrikvilhelmberglund @niktek FYI I've moved this over to the proper project repo. Thanks for the suggestion!

**Comment by henrikvilhelmberglund** [comment]
> @henrikvilhelmberglund @niktek FYI I've moved this over to the proper project repo. Thanks for the suggestion!

Woops, thanks. 😄

**Comment by niktek** [comment]
Just want to check here - is this into a new empty folder or an existing install?  Because SK will overwrite an existing install and blow away all your changes, which is why I added that check in there.  I could tweak the check to make sure the folder is empty, but it gets super complicated to try and reason with an existing install and overlay the skeleton stuff on top without breaking things.

**Comment by niktek** [comment]
This is now updated to allow install into a current empty directory
