### ISSUE TITLE
Receiving `Semicolon or block is expected` errors in VSCode

### ISSUE THREAD

**Issue by BrianLYS** [skeletonlabs/create-skeleton-app#26]
Hello,

I've ran the command `npm create skeleton-app@latest my-skeleton-app` in my CLI and I'm receiving this error in VSCode.
Not sure what the fix for this is.

![image](https://user-images.githubusercontent.com/83122861/236784052-97e2e4b3-b323-47d7-9084-db5b365382ee.png)

**Comment by Sarenor** [comment]
Can you share the repository where you ran the command?

**Comment by BrianLYS** [comment]
Sure thing @Sarenor, https://github.com/BrianLYS/SvelteKitTest here ya go.
The issue is in the +page.svelte on first create with `npm create skeleton-app@latest website`

**Comment by endigo9740** [comment]
@niktek pinging you to bring attention to this as well

**Comment by endigo9740** [comment]
FYI I've cloned down the project and ran it locally, but I'm unable to replicate the issue.

![Screenshot 2023-05-08 at 10 42 59 AM](https://user-images.githubusercontent.com/1509726/236868545-29693dab-cc89-41b5-93b2-cf98a5f8e84a.png)

Can you confirm you've run the `npm run dev` command to start the local server at least once? There's some things that SvelteKit creates on first run that if not present can give odd errors like this at times. Maybe try that?

Try restarting VS Code as well. I've had it throw odd errors at me at times that are gone when I reload.

The only thing else that stood out a bit odd to me was that you moved the whole project into a `/website` directory instead of keeping it in root. We typically only see that when folks are building monorepos, though I don't see any of that here. Just note our our FAQ we don't official support monorepos, given the extra complexity they introduce.
https://www.skeleton.dev/docs/introduction

That doesn't mean they don't work (I know of other devs using Skeleton within monorepose successfully), it just means what I said - we don't provide official support for these if something goes wrong.

**Comment by BrianLYS** [comment]
Yes, I've ran `npm run dev` and the app starts up just fine, which didn't solve the issue for me.

However the explanation about monorepos did, once I opened only the website folder instead of the root. I can see that the linting works !

![image](https://user-images.githubusercontent.com/83122861/236870919-459f221f-4a3b-47ae-998b-3322ae3ce30f.png)
