### ISSUE TITLE
Skeleton CLI uses old version of sveltekit

### ISSUE THREAD

**Issue by cemkaan** [skeletonlabs/create-skeleton-app#39]
Skeleton CLI installed svelte 3 but current version is "svelte": "^4.2.0",

**Comment by endigo9740** [comment]
@cemkaan this is by design. We pin the version to ensure compatibility. For example, when Svelte v4 dropped recently it came quickly and with little heads up publicly the day of. Skeleton release don't always align with Svelte releases. If we hadn't pinned the version folks would have been getting v4 by default, which had a few minor breaking changes we had to address on our end.

That said, you are free to update as desired on your end and test it out. Just make sure to test thoroughly before you commit and deploy to a production environment. And of course, if you discover issues, please feel free to report them to the core library project so we can update accordingly!

**Comment by cemkaan** [comment]
**OK** There are compability isues with svelte 4. 

I tried on fresh Svelte 4 , tailwind , @tailwindcss/forms , [@tailwindcss/typography - Tailwind CSS](https://tailwindcss.com/docs/typography-plugin)
my sveltekit app says:
```
[plugin:vite:css] [postcss] Cannot use 'in' operator to search for 'properties' in undefined
D:/sveltekitapp/src/app.css
```

It seems I will start my project with Svelte 3 then migrate to Svelte 4
